version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      npm-major:
        update-types:
          - "major"
      npm-minor:
        update-types:
          - "minor"
          - "patch"
