name: Build Release Package

on:
  push:
    branches:
      - main

jobs:
  build-release:
    name: Build release package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build main.js
        run: |
          npm ci
          npm run build
          mkdir dist
          cp main.js dist/
          cp manifest.json dist/
          cp styles.css dist/
          cp LICENSE.md dist/
          cp README.md dist/

      - uses: actions/upload-artifact@v4
        with:
          name: obsidian-wakatime-wakapi-package
          retention-days: 7
          path: dist
