name: Build Release Package

on:
  push:
    branches:
      - main

jobs:
  build-release:
    name: Build release package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build main.js
        run: |
          npm ci
          npm run build
          mkdir obsidian-wakatime-wakapi
          mv main.js obsidian-wakatime-wakapi/
          mv manifest.json obsidian-wakatime-wakapi/
          mv styles.css obsidian-wakatime-wakapi/
          mv LICENSE.md obsidian-wakatime-wakapi/
          mv README.md obsidian-wakatime-wakapi/

      - uses: actions/upload-artifact@v4
        with:
          name: release-package
          retention-days: 7
          path: obsidian-wakatime-wakapi
